name: Deploy Backend (SSH)

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy over SSH (minimal update to prisma and pm2)
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT || 22 }}
                  script: |
                      set -euo pipefail

                      APP_DIR="$HOME/CAT4U_WEB_BACKEND"
                      REPO="https://github.com/4cozm/CAT4U_WEB_BACKEND.git"
                      BRANCH="main"
                      PROC="cat4u-backend"

                      command -v git >/dev/null 2>&1 || { sudo apt-get update -y && sudo apt-get install -y git; }
                      command -v pm2 >/dev/null 2>&1 || sudo npm i -g pm2

                      # repo 보장(최초 1회 clone)
                      mkdir -p "$APP_DIR"
                      if [ ! -d "$APP_DIR/.git" ]; then
                        git clone --branch "$BRANCH" --depth 1 "$REPO" "$APP_DIR"
                      fi

                      cd "$APP_DIR"

                      # ✅ 배포 중 husky 완전 차단
                      git config --local core.hooksPath /dev/null || true
                      export HUSKY=0
                      export HUSKY_SKIP_INSTALL=1

                      # 업데이트(항상 최신으로)
                      git remote set-url origin "$REPO"
                      git fetch origin "$BRANCH" --depth 1
                      git checkout "$BRANCH"
                      git reset --hard "origin/$BRANCH"

                      export NODE_ENV=production
                      # prisma가 devDep → dev 생략 금지. 스크립트만 비활성화해 husky 방지
                      npm ci --ignore-scripts

                      npx prisma generate
                      if [ -d prisma/migrations ] && [ "$(ls -A prisma/migrations)" ]; then
                        npx prisma migrate deploy
                      fi

                      # PM2: 있으면 reload, 없으면 start
                      pm2 describe "$PROC" >/dev/null 2>&1 \
                        && pm2 reload "$PROC" --update-env \
                        || pm2 start npm --name "$PROC" -i max -- run start

                      pm2 save
